### PR TITLE
Added ability to define the model

### PR DESCRIPTION
**Pull request by IbragimovDP**

### CODE REVIEW

**Comment by JCharante** [comment]
why did package-lock.json change if package.json didn't?

**Comment by clairefro** [comment]
@JCharante - looks like the diff is formatting change only (indentation). I should probably add a prettier config file to the project later

**Comment by JCharante** [comment]
Prettier could work, or just a .editorconfig file for anybody who uses an IDE so it doesn't change the indentation anymore.

**Comment by clairefro** [comment]
Ready to merge this one suggestions are reviewed: https://github.com/IbragimovDP/obsidian-chat-cbt-plugin/pull/1

**Comment by IbragimovDP** [comment]
Sorry for long responses and thank you for your help🫶
I've finished my side

**Comment by clairefro** [comment]
@IbragimovDP 
Perfect! Thanks for kicking off this high demand feature and being the first contributor :)

**Pull request merged**
